apiVersion: v1
kind: Secret
metadata:
  name: {{ include "intel-ark-bot.fullname" . }}
  labels:
    {{ include "intel-ark-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secretEnvVars | nindent 2 }}
